# Generated by Django 4.2.13 on 2025-09-24 11:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GestureSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_name', models.CharField(default='Untitled Session', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gesture Session',
                'verbose_name_plural': 'Gesture Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceToSign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_file', models.FileField(upload_to='voice_files/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav', 'mp3', 'm4a'])])),
                ('transcribed_text', models.TextField(blank=True, null=True)),
                ('output_video', models.FileField(blank=True, null=True, upload_to='voice_to_sign/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('transcribing', 'Transcribing'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_conversions', to='video_app.gesturesession')),
            ],
            options={
                'verbose_name': 'Voice to Sign Conversion',
                'verbose_name_plural': 'Voice to Sign Conversions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TextToSign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_text', models.TextField()),
                ('output_video', models.FileField(blank=True, null=True, upload_to='text_to_sign/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_conversions', to='video_app.gesturesession')),
            ],
            options={
                'verbose_name': 'Text to Sign Conversion',
                'verbose_name_plural': 'Text to Sign Conversions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=10)),
                ('message', models.TextField()),
                ('module', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video_app.gesturesession')),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HandGesture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gesture_type', models.CharField(choices=[('السلام عليكم', 'السلام عليكم'), ('مع السلامه', 'مع السلامه'), ('كيف الحال', 'كيف الحال'), ('مهندس', 'مهندس')], max_length=50)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='gesture_videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov'])])),
                ('processed_video', models.FileField(blank=True, null=True, upload_to='processed_videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestures', to='video_app.gesturesession')),
            ],
            options={
                'verbose_name': 'Hand Gesture',
                'verbose_name_plural': 'Hand Gestures',
                'ordering': ['-created_at'],
            },
        ),
    ]
